name: CI - Build, Test and Generate Docs

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Устанавливаем зависимости (Qt6 и прочее)
      - name: Install Qt6 dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            qt6-base-dev \
            qt6-qmake \
            qt6-tools-dev \
            libqt6widgets6 \
            libxcb1 \
            libx11-dev \
            libglu1-mesa \
            doxygen \
            graphviz

      # Устанавливаем зависимость Catch2
      - name: Install Catch2
        run: |
          sudo apt-get install -y catch2

      # Устанавливаем переменные среды для Qt6
      - name: Set up Qt6 environment
        run: |
          export QT_QPA_PLATFORM=offscreen
          export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/qt6/plugins/platforms

      # Создаем сборочную директорию и компилируем проект
      - name: Build the project
        run: |
          mkdir -p build && cd build
          cmake ..
          make

      # Запуск тестов
      - name: Run tests
        run: |
          cd build/tests
          ./tests --success

      # Генерация документации
      - name: Generate Documentation
        run: |
          doxygen docs/Doxyfile
          ls -la docs/output/html/

      # Загружаем артефакты
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: calculator-app
          path: build/src/Calculator
          retention-days: 7

      - name: Upload Documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: docs/output/html/
          retention-days: 7
          if-no-files-found: warn
